---
- name: 'Instala pacotes de dependencia do MySQL'
  apt:
    name: '{{ item }}'
    state: 'latest'
  become: yes
  with_items:
    - mysql-server-5.6
    - python-mysqldb

- name: 'Criar banco do MySQL'
  mysql_db:
    name: '{{ wp_db_name }}'
    login_user: root
    state: present

- name: Criar o usuário do MySQL
  community.mysql.mysql_user:
    login_user: root
    name: '{{ wp_username }}'
    password: '{{ wp_user_password }}'
    priv: '{{ wp_db_name }}.*:ALL'
    state: present
    host: '{{ item }}'
  with_items:
    - '{{ wp_host_ip }}'

- name: 'Configura o MySQL para aceitar conexões remotas'
  ansible.builtin.copy:
    src: files/my.cnf
    dest: /etc/mysql/my.cnf
  become: yes
  notify:
    - restart mysql